force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Nome da cidade onde o local está situado.</description>
    <inlineHelpText>Informe a cidade.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Código de endereçamento postal (CEP).</description>
    <inlineHelpText>Digite o código postal.</inlineHelpText>
    <label>Postal Code</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Estado ou província do endereço.</description>
    <inlineHelpText>Informe a sigla ou nome do estado.</inlineHelpText>
    <label>State</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LocationTriggerHandler.cls
public class LocationTriggerHandler {

    public static void aposInserir(List<Location__c> novasLocalizacoes) {
        List<Id> idsParaProcessar = new List<Id>();
        
        for (Location__c localizacao : novasLocalizacoes) {
            if (localizacao.Name != null || localizacao.City__c != null || localizacao.State__c != null || localizacao.Postal_Code__c != null) {
                idsParaProcessar.add(localizacao.Id);
            }
        }
        
        if (!idsParaProcessar.isEmpty()) {
            SmartyStreetsService.verificarEnderecos(idsParaProcessar);
        }
    }

    public static void aposAtualizar(List<Location__c> novasLocalizacoes, Map<Id, Location__c> mapaAntigoLocalizacoes) {
        List<Id> idsParaProcessar = new List<Id>();
        
        for (Location__c localizacaoNova : novasLocalizacoes) {
            Location__c localizacaoAntiga = mapaAntigoLocalizacoes.get(localizacaoNova.Id);
            
            // Monitoriza alterações, comparando o campo 'Name' (Street)
            if (localizacaoNova.Name != localizacaoAntiga.Name || 
                localizacaoNova.City__c != localizacaoAntiga.City__c || 
                localizacaoNova.State__c != localizacaoAntiga.State__c || 
                localizacaoNova.Postal_Code__c != localizacaoAntiga.Postal_Code__c) {
                
                idsParaProcessar.add(localizacaoNova.Id);
            }
        }
        
        if (!idsParaProcessar.isEmpty()) {
            SmartyStreetsService.verificarEnderecos(idsParaProcessar);
        }
    }
}