force-app/main/default/objects/Medical_Event__c/Medical_Event__c.object-meta.xml
<CustomObject>
    <label>Medical Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Data e hora de término programada para o evento.</description>
    <inlineHelpText>Informe o dia e o horário que o evento encerra.</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o evento é transmitido ao vivo/online.</description>
    <inlineHelpText>Marque se o evento for uma transmissão em tempo real.</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PurgeOldEventsBatch.cls
public class PurgeOldEventsBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        Date doisMesesPassados = Date.today().addMonths(-2);
        
        return Database.getQueryLocator([
            SELECT Id 
            FROM Medical_Event__c 
            WHERE Live__c = false 
            AND End__c < :doisMesesPassados
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Medical_Event__c> scope) {
        MedicalEventBatchHandler.deletarEventosAntigos(scope);
    }

    public void finish(Database.BatchableContext BC) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        mail.setToAddresses(new String[] {'sfdcpanther@gmail.com'});
        mail.setSubject('Execução do Batch Concluída: Exclusão de Eventos Médicos');
        mail.setPlainTextBody('Olá, \n\nO batch Apex para excluir registros antigos de Eventos Médicos foi concluído com sucesso.\n\nAtenciosamente, \nSistema OrganizaMed');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}