force-app/main/default/objects/Event_Speaker__c/fields/Medical_Event__c.field-meta.xml
<CustomField>
    <fullName>Medical_Event__c</fullName>
    <description>Mestre no relacionamento para controle de palestrantes.</description>
    <inlineHelpText>Selecione o evento onde o palestrante atuará.</inlineHelpText>
    <label>Medical Event</label>
    <referenceTo>Medical_Event__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Detalhe que vincula o palestrante ao evento.</description>
    <inlineHelpText>Selecione o palestrante convidado para este evento.</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Event__c/Medical_Event__c.object-meta.xml
<CustomObject>
    <label>Medical Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Título ou nome descritivo do evento médico.</description>
    <inlineHelpText>Digite o nome do workshop, palestra ou consulta.</inlineHelpText>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerTriggerHandlerTest.cls
//Classe teste unitário da classe organizadora de eventoss

@isTest
private class EventSpeakerTriggerHandlerTest {
    
    @testSetup
    static void setupTestData() {
        TestDataFactory.createEvent('Congresso de Cardiologia', true);
        TestDataFactory.createEvent('Workshop de Pediatria', true);
        TestDataFactory.createSpeaker(true);
    }
    // Teste Milestone 3
    @isTest
    static void testPreventDuplicateSpeaker() {
        Medical_Event__c event1 = [SELECT Id FROM Medical_Event__c WHERE Name__c = 'Congresso de Cardiologia' LIMIT 1];
        Medical_Event__c event2 = [SELECT Id FROM Medical_Event__c WHERE Name__c = 'Workshop de Pediatria' LIMIT 1];
        Speaker__c speaker = [SELECT Id FROM Speaker__c LIMIT 1];

        Event_Speaker__c es1 = new Event_Speaker__c(
            Medical_Event__c = event1.Id, 
            Speaker__c = speaker.Id
        );
        insert es1;
        
        Event_Speaker__c es2 = new Event_Speaker__c(
            Medical_Event__c = event2.Id, 
            Speaker__c = speaker.Id
        );
        
        Test.startTest();
        Boolean errorThrown = false;
        try {
            insert es2; 
        } catch (Exception ex) {
            errorThrown = true;
            System.assert(ex.getMessage().contains('Este palestrante já possui um evento ativo agendado'), 'A mensagem de erro foi diferente da esperada.');
        }
        Test.stopTest();

        System.assert(errorThrown, 'O teste falhou: O sistema permitiu agendar o palestrante em dois eventos simultâneos.');
    }

    // Teste Milestone 4
    @isTest
    static void testSendConfirmationEmail() {
        Medical_Event__c event1 = [SELECT Id FROM Medical_Event__c WHERE Name__c = 'Congresso de Cardiologia' LIMIT 1];
        Speaker__c speaker = [SELECT Id FROM Speaker__c LIMIT 1];
        
        Event_Speaker__c es = new Event_Speaker__c(
            Medical_Event__c = event1.Id,
            Speaker__c = speaker.Id
        );

        Test.startTest();
        insert es;
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        
        System.assertEquals(1, emailInvocations, 'O sistema deveria ter disparado exatamente 1 e-mail de confirmação.');
    }
}